version: '2'

services:
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
    volumes:
      - ./config:/config
      - ./data/consul:/consul/data
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1

  vault:
    container_name: vault
    image: vault:latest
    links:
      - consul:consul
    depends_on:
      - consul
    ports:
      - "8200:8200"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./scripts:/scripts
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    command: server -config=/config/vault.hcl

  webui:
    container_name: webui
    image: djenriquez/vault-ui
    ports:
      - "8000:8000"
    links:
      - vault:vault
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: USERNAMEPASSWORD
